services:
  mysql:
    image: mysql:8.0
    container_name: transparency-database-sandbox-mysql
    environment:
      MYSQL_DATABASE: transparency_sandbox
      MYSQL_USER: transparency
      MYSQL_PASSWORD: transparency
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -proot --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
