services:
    web:
        image: nginx:latest
        container_name: web
        volumes:
            - .:/var/www/html
            - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - php
        networks:
            - transparencydb-network

    php:
        build: ./.docker/php
        container_name: php
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - transparencydb-network

    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: transparencydb
        ports:
            - "3306:3306"
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        networks:
            - transparencydb-network
    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        command: /bin/sh -c "redis-server --requirepass secret"
        ports:
            - "6379:6379"
        volumes:
            - ./storage/docker/redis:/data
        networks:
            - transparencydb-network

    opensearch:
        image: opensearchproject/opensearch:2.11.0
        container_name: opensearch
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
            - OPENSEARCH_INITIAL_ADMIN_PASSWORD=secret
            - plugins.security.disabled=true
            # Disable problematic plugin
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
        volumes:
            - ./storage/docker/opensearch:/usr/share/opensearch/data
        networks:
            - transparencydb-network

networks:
    transparencydb-network:
        driver: bridge
