<?php

namespace Tests\Feature\Services;

use App\Models\DayArchive;
use App\Models\Statement;
use App\Services\DayArchiveService;
use App\Services\DriveInService;
use App\Services\EuropeanCountriesService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Http;
use Tests\TestCase;

class DayArchiveServiceTest extends TestCase
{

    use RefreshDatabase;

    protected DayArchiveService $day_archive_service;
    private array $required_fields;

    public function setUp(): void
    {
        $this->day_archive_service = app(DayArchiveService::class);
        $this->assertNotNull($this->day_archive_service);
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->required_fields = [
            'decision_visibility' => ['DECISION_VISIBILITY_CONTENT_DISABLED','DECISION_VISIBILITY_CONTENT_AGE_RESTRICTED'],
            'decision_ground' => 'DECISION_GROUND_ILLEGAL_CONTENT',
            'category' => 'STATEMENT_CATEGORY_ANIMAL_WELFARE',
            'illegal_content_legal_ground' => 'foo',
            'illegal_content_explanation' => 'bar',
            'puid' => 'TK421',
            'territorial_scope' => ['BE', 'DE', 'FR'],
            'source_type' => 'SOURCE_ARTICLE_16',
            'source_identity' => 'foo',
            'decision_facts' => 'decision and facts',
            'content_type' => ['CONTENT_TYPE_SYNTHETIC_MEDIA'],
            'automated_detection' => 'No',
            'automated_decision' => 'AUTOMATED_DECISION_PARTIALLY',
            'application_date' => '2023-05-18',
            'content_date' => '2023-05-18'
        ];
    }

    /**
     * @test
     */
    public function it_retrieves_global_list()
    {
        DayArchive::create([
            'date' => '2023-10-02',
            'total' => 1,
            'completed_at' => Carbon::now()
        ]);
        DayArchive::create([
            'date' => '2023-10-01',
            'total' => 2,
            'completed_at' => Carbon::now()
        ]);


        $list = $this->day_archive_service->globalList()->get();
        $this->assertCount(2, $list);

        // First one needs the 2
        $first = $list->first();
        $this->assertEquals('2023-10-02', $first->date);

        // Needs to be in the right order.
        $last = $list->last();
        $this->assertEquals('2023-10-01', $last->date);

    }

    /**
     * @test
     */
    public function gloabl_list_must_be_completed_day_archive()
    {
        DayArchive::create([
            'date' => '2023-10-02',
            'total' => 1
        ]);
        DayArchive::create([
            'date' => '2023-10-01',
            'total' => 2
        ]);


        $list = $this->day_archive_service->globalList()->get();
        $this->assertCount(0, $list);
    }

    /**
     * @test
     */
    public function it_retrieves_an_archive_by_date()
    {
        DayArchive::create([
            'date' => '2023-10-02',
            'total' => 1
        ]);

        $dayarchive = $this->day_archive_service->getDayArchiveByDate(Carbon::createFromFormat('Y-m-d', '2023-10-02'));
        $this->assertNotNull($dayarchive);
    }

    /**
     * @test
     */
    public function it_creates_a_day_archive()
    {
        $day_archive = $this->day_archive_service->createDayArchive(Carbon::createFromFormat('Y-m-d', '2023-10-02'));
        $this->assertTrue($day_archive);
    }

    /**
     * @test
     */
    public function it_does_not_allow_overwriting()
    {
        $day_archive = $this->day_archive_service->createDayArchive(Carbon::createFromFormat('Y-m-d', '2023-10-02'));
        $this->assertNotNull($day_archive);

        $this->expectExceptionMessage('A day archive for the date: 2023-10-02 already exists.');
        $day_archive = $this->day_archive_service->createDayArchive(Carbon::createFromFormat('Y-m-d', '2023-10-02'));
    }


    /**
     * @test
     */
    public function it_ensures_the_date_is_in_the_past()
    {
        $this->expectExceptionMessage('When creating a day export you must supply a date in the past.');
        $day_archive = $this->day_archive_service->createDayArchive(Carbon::createFromFormat('Y-m-d', '2070-10-02'));
    }

    /**
     * @test
     * @return void
     */
    public function it_gets_the_first_id_from_date()
    {
        $this->setUpFullySeededDatabase();
        $admin = $this->signInAsAdmin();
        $fields_one = $this->required_fields;
        $fields_two = $this->required_fields;

        $fields_one['user_id'] = $admin->id;
        $fields_one['platform_id'] = $admin->platform->id;
        $fields_one['created_at'] = '2030-01-01 00:00:10'; // also prove the while loop works

        $fields_two['puid'] = 'TK422';
        $fields_two['user_id'] = $admin->id;
        $fields_two['platform_id'] = $admin->platform->id;
        $fields_two['created_at'] = '2030-01-01 00:00:10';

        $statement_one = Statement::create($fields_one);
        $statement_two = Statement::create($fields_two);

        $this->assertLessThan($statement_two->id, $statement_one->id);

        $first_id = $this->day_archive_service->getFirstIdOfDate(Carbon::createFromDate(2030, 1, 1));

        $this->assertEquals($statement_one->id, $first_id);
    }

    /**
     * @test
     * @return void
     */
    public function it_gets_zero_on_first()
    {
        $this->setUpFullySeededDatabase();
        $admin = $this->signInAsAdmin();

        $first_id = $this->day_archive_service->getFirstIdOfDate(Carbon::createFromDate(2030, 1, 1));

        $this->assertEquals(0, $first_id);
    }

    /**
     * @return void
     * @test
     */
    public function it_builds_a_nice_array_for_the_start_of_a_date(): void
    {
        $in = $this->day_archive_service->buildStartOfDateArray(Carbon::now());
        $this->assertNotNull($in);
        $this->assertCount(500, $in);
        $this->assertContains(Carbon::now()->format('Y-m-d 00:00:00'), $in);
        $this->assertContains(Carbon::now()->format('Y-m-d 00:08:19'), $in);
    }

    /**
     * @return void
     * @test
     */
    public function it_builds_a_nice_array_for_the_end_of_a_date(): void
    {
        $in = $this->day_archive_service->buildEndOfDateArray(Carbon::now());
        $this->assertNotNull($in);
        $this->assertCount(500, $in);
        $this->assertContains(Carbon::now()->format('Y-m-d 23:59:59'), $in);
        $this->assertContains(Carbon::now()->format('Y-m-d 23:51:40'), $in);
    }

    /**
     * @test
     * @return void
     */
    public function it_gets_the_last_id_from_date()
    {
        $this->setUpFullySeededDatabase();
        $admin = $this->signInAsAdmin();
        $fields_one = $this->required_fields;
        $fields_two = $this->required_fields;

        $fields_one['user_id'] = $admin->id;
        $fields_one['platform_id'] = $admin->platform->id;
        $fields_one['created_at'] = '2030-01-01 23:59:40'; // also prove the while loop works

        $fields_two['puid'] = 'TK422';
        $fields_two['user_id'] = $admin->id;
        $fields_two['platform_id'] = $admin->platform->id;
        $fields_two['created_at'] = '2030-01-01 23:59:40';

        $statement_one = Statement::create($fields_one);
        $statement_two = Statement::create($fields_two);

        $this->assertLessThan($statement_two->id, $statement_one->id);

        $last_id = $this->day_archive_service->getLastIdOfDate(Carbon::createFromDate(2030, 1, 1));

        $this->assertEquals($statement_two->id, $last_id);
    }

    /**
     * @test
     * @return void
     */
    public function it_gets_zero_on_last()
    {
        $this->setUpFullySeededDatabase();
        $admin = $this->signInAsAdmin();

        $last_id = $this->day_archive_service->getLastIdOfDate(Carbon::createFromDate(2030, 1, 1));

        $this->assertEquals(0, $last_id);
    }
}
