<?php

namespace Tests\Feature\Services;

use App\Services\EuropeanLanguagesService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class EuropeanLanguagesServiceTest extends TestCase
{

    use RefreshDatabase;

    protected EuropeanLanguagesService $european_languages_service;

    public function setUp(): void
    {
        $this->european_languages_service = app(EuropeanLanguagesService::class);
        $this->assertNotNull($this->european_languages_service);
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    /**
     * @return void
     * @test
     */
    public function it_gives_back_european_languages()
    {
        $result = $this->european_languages_service->getEuropeanLanguages();
        $this->assertNotNull($result);
        $this->assertIsArray($result);
        $this->assertEquals(count(EuropeanLanguagesService::EUROPEAN_LANGUAGE_CODES), count($result));
    }

    /**
     * @return void
     * @test
     */
    public function it_gives_back_all_languages_codes()
    {
        $result = $this->european_languages_service->getAllLanguages();
        $this->assertIsArray($result);
        $this->assertCount(184, $result);
    }

    /**
     * @return void
     * @test
     */
    public function it_gives_back_all_languages_codes_euro_first()
    {
        $result = $this->european_languages_service->getAllLanguages(true);
        $this->assertIsArray($result);
        $this->assertCount(184, $result);
    }
}
