<?php

namespace Tests\Feature\Services;

use App\Models\Statement;
use App\Services\StatementStatsService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;


class StatementStatsServiceTest extends TestCase
{
    use RefreshDatabase;

    protected StatementStatsService $statement_stats_service;

    public function setUp(): void
    {
        $this->statement_stats_service = app(StatementStatsService::class);
        $this->assertNotNull($this->statement_stats_service);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function it_can_do_the_total()
    {
        $this->seed(); // 10 statements
        Statement::factory()->count(10)->create();
        $total = $this->statement_stats_service->totalStatements();
        $this->assertEquals(10, $total);
    }

}
